name: personal-allowance
dependencies:
- python
- plotly
- pandas
- numpy
- pip
- pip:
  - jupyter-book
  - "git+https://github.com/PSLmodels/openfisca-uk"
  - "git+https://github.com/PSLmodels/microdf"
